Repository Mt-Ugh/apt.zip_be, pull requests merged in 2025-05, with the labels that each got.

#3 feat: 실거래 지역 조회 API 추가
  src/main/java/com/aptzip/dealMap/controller/DealMapController.java
  src/main/java/com/aptzip/dealMap/dto/request/DongRequest.java
  src/main/java/com/aptzip/dealMap/dto/request/GugunRequest.java
  src/main/java/com/aptzip/dealMap/dto/response/DongResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/GugunResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/SidoResponse.java
  src/main/java/com/aptzip/dealMap/entity/DongCode.java
  src/main/java/com/aptzip/dealMap/repository/DealMapRepository.java
  src/main/java/com/aptzip/dealMap/service/DealMapService.java
Labels: feat

#6 fix: 실거래 지역 조회 API 수정
  src/main/java/com/aptzip/dealMap/controller/DealMapController.java
  src/main/java/com/aptzip/dealMap/dto/request/DongRequest.java
  src/main/java/com/aptzip/dealMap/dto/request/GugunRequest.java
  src/main/java/com/aptzip/dealMap/repository/DealMapRepository.java
  src/main/java/com/aptzip/dealMap/service/DealMapService.java
Labels: fix

#7 feat: 로그인 및 회원가입 API 추가
  pom.xml
  src/main/java/com/aptzip/AptzipApplication.java
  src/main/java/com/aptzip/auth/controller/AuthController.java
  src/main/java/com/aptzip/auth/dto/request/SigninRequest.java
  src/main/java/com/aptzip/auth/dto/response/TokenResponse.java
  src/main/java/com/aptzip/auth/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/aptzip/auth/oauth/OAuth2SuccessHandler.java
  src/main/java/com/aptzip/auth/oauth/OAuth2UserCustomService.java
  src/main/java/com/aptzip/auth/repository/RedisRefreshTokenRepository.java
  src/main/java/com/aptzip/auth/service/AuthService.java
  src/main/java/com/aptzip/common/config/CorsConfig.java
  src/main/java/com/aptzip/common/config/CorsProperties.java
  src/main/java/com/aptzip/common/config/RedisConfig.java
  src/main/java/com/aptzip/common/config/RedisProperties.java
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
  src/main/java/com/aptzip/common/config/jwt/JwtProperties.java
  src/main/java/com/aptzip/common/config/jwt/TokenProvider.java
  src/main/java/com/aptzip/common/filter/TokenAuthenticationFilter.java
  src/main/java/com/aptzip/common/util/CookieUtil.java
  src/main/java/com/aptzip/user/controller/UserController.java
  src/main/java/com/aptzip/user/dto/request/AddUserRequest.java
  src/main/java/com/aptzip/user/entity/User.java
  src/main/java/com/aptzip/user/repository/UserRepository.java
  src/main/java/com/aptzip/user/service/UserService.java
  src/main/resources/application-example.properties
  src/main/resources/application.properties
Labels: feat

#10 feat: 로그인 API 반환값 수정 및 공개 엔드포인트 추가
  src/main/java/com/aptzip/auth/controller/AuthController.java
  src/main/java/com/aptzip/auth/dto/response/LoginResponse.java
  src/main/java/com/aptzip/auth/dto/response/TokenResponse.java
  src/main/java/com/aptzip/auth/dto/response/TokenUserResponse.java
  src/main/java/com/aptzip/auth/dto/response/TokensResponse.java
  src/main/java/com/aptzip/auth/service/AuthService.java
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
  src/main/java/com/aptzip/common/config/jwt/TokenProvider.java
  src/main/java/com/aptzip/common/filter/TokenAuthenticationFilter.java
Labels: feat, fix

#12 feat: 사용자 관련 기능 추가
  src/main/java/com/aptzip/user/controller/UserController.java
  src/main/java/com/aptzip/user/dto/request/UpdateProfileUrlRequest.java
  src/main/java/com/aptzip/user/dto/request/UpdateUserRequest.java
  src/main/java/com/aptzip/user/dto/response/UserDetailResponse.java
  src/main/java/com/aptzip/user/entity/User.java
  src/main/java/com/aptzip/user/repository/UserRepository.java
  src/main/java/com/aptzip/user/service/UserService.java
Labels: feat

#13 feat: 실거래 매물 목록 조회 API 추가
  src/main/java/com/aptzip/dealMap/controller/DealMapController.java
  src/main/java/com/aptzip/dealMap/dto/request/DealListRequest.java
  src/main/java/com/aptzip/dealMap/dto/response/DealListResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/DongResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/GugunResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/SidoResponse.java
  src/main/java/com/aptzip/dealMap/entity/HouseDeal.java
  src/main/java/com/aptzip/dealMap/entity/HouseInfo.java
  src/main/java/com/aptzip/dealMap/repository/DealHouseRepository.java
  src/main/java/com/aptzip/dealMap/repository/DealMapDongRepository.java
  src/main/java/com/aptzip/dealMap/service/DealMapService.java
Labels: feat

#15 fix: 인증 엔드포인트 설정 수정
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
Labels: fix

#16 feat: 실거래 매물 상세 조회 API 추가
  src/main/java/com/aptzip/dealMap/controller/DealMapController.java
  src/main/java/com/aptzip/dealMap/dto/request/DetailRequest.java
  src/main/java/com/aptzip/dealMap/dto/response/DetailListResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/DetailResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/DetailWrapperResponse.java
  src/main/java/com/aptzip/dealMap/entity/HouseDeal.java
  src/main/java/com/aptzip/dealMap/repository/DetailDealRepository.java
  src/main/java/com/aptzip/dealMap/repository/DetailRepository.java
  src/main/java/com/aptzip/dealMap/service/DealMapService.java
Labels: feat, fix

#19 fix: SecurityContext에 User 주입 및 조회하도록 수정
  src/main/java/com/aptzip/common/config/jwt/TokenProvider.java
  src/main/java/com/aptzip/user/controller/UserController.java
Labels: fix

#23 fix: 모든 서버 예외 401 Unauthorized 반환 문제 수정
  src/main/java/com/aptzip/auth/dto/request/SigninRequest.java
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
  src/main/java/com/aptzip/common/config/cors/CorsConfig.java
  src/main/java/com/aptzip/common/config/cors/CorsProperties.java
  src/main/java/com/aptzip/common/config/redis/RedisConfig.java
  src/main/java/com/aptzip/common/config/redis/RedisProperties.java
  src/main/java/com/aptzip/common/filter/TokenAuthenticationFilter.java
  src/main/java/com/aptzip/common/handler/GlobalExceptionHandler.java
  src/main/java/com/aptzip/user/controller/UserController.java
  src/main/java/com/aptzip/user/repository/UserRepository.java
  src/main/java/com/aptzip/user/service/UserService.java
Labels: bug, fix

#26 feat: 주변 편의 시설 조회 API 추가
  src/main/java/com/aptzip/amenitiesMap/controller/AmenitiesMapController.java
  src/main/java/com/aptzip/amenitiesMap/dto/request/AmenitiesListRequest.java
  src/main/java/com/aptzip/amenitiesMap/dto/response/AmenitiesListResponse.java
  src/main/java/com/aptzip/amenitiesMap/entity/CommercialPlace.java
  src/main/java/com/aptzip/amenitiesMap/repository/AmenitiesMapRepository.java
  src/main/java/com/aptzip/amenitiesMap/service/AmenitiesMapService.java
Labels: feat

#20 feat: 관심 지역 관련 기능 추가
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
  src/main/java/com/aptzip/dealMap/controller/DealMapController.java
  src/main/java/com/aptzip/dealMap/dto/request/DealListRequest.java
  src/main/java/com/aptzip/dealMap/dto/response/DetailListResponse.java
  src/main/java/com/aptzip/dealMap/entity/DongCode.java
  src/main/java/com/aptzip/dealMap/repository/DealHouseRepository.java
  src/main/java/com/aptzip/dealMap/repository/DetailDealRepository.java
  src/main/java/com/aptzip/dealMap/repository/DetailRepository.java
  src/main/java/com/aptzip/dealMap/service/DealMapService.java
  src/main/java/com/aptzip/interestArea/controller/InterestAreaController.java
  src/main/java/com/aptzip/interestArea/dto/request/AddInterestAreaRequest.java
  src/main/java/com/aptzip/interestArea/dto/response/FameListResponse.java
  src/main/java/com/aptzip/interestArea/dto/response/InterestListResponse.java
  src/main/java/com/aptzip/interestArea/entity/Area.java
  src/main/java/com/aptzip/interestArea/entity/InterestArea.java
  src/main/java/com/aptzip/interestArea/repositiory/AreaRepository.java
  src/main/java/com/aptzip/interestArea/repositiory/InterestRepository.java
  src/main/java/com/aptzip/interestArea/service/InterestAreaService.java
  src/main/resources/application-example.properties
Labels: feat, chore

#24 feat: QnA 관련 기능 추가
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
  src/main/java/com/aptzip/qna/constant/Category.java
  src/main/java/com/aptzip/qna/controller/QnAController.java
  src/main/java/com/aptzip/qna/dto/request/AnswerRequest.java
  src/main/java/com/aptzip/qna/dto/request/QnARegistRequest.java
  src/main/java/com/aptzip/qna/dto/response/DetailResponse.java
  src/main/java/com/aptzip/qna/dto/response/DetailWrapperResponse.java
  src/main/java/com/aptzip/qna/dto/response/QnAAnswerResponse.java
  src/main/java/com/aptzip/qna/dto/response/QnAListResponse.java
  src/main/java/com/aptzip/qna/dto/response/RegistResponse.java
  src/main/java/com/aptzip/qna/entity/Answer.java
  src/main/java/com/aptzip/qna/entity/QnA.java
  src/main/java/com/aptzip/qna/repository/AnswerRepository.java
  src/main/java/com/aptzip/qna/repository/QnARepository.java
  src/main/java/com/aptzip/qna/service/QnAService.java
Labels: feat, fix

#30 feat: 뉴스 목록 조회 API 추가
  pom.xml
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
  src/main/java/com/aptzip/common/config/redis/RedisConfig.java
  src/main/java/com/aptzip/news/controller/NewsController.java
  src/main/java/com/aptzip/news/dto/request/NewsRequest.java
  src/main/java/com/aptzip/news/dto/response/NewsResponse.java
  src/main/java/com/aptzip/news/service/NewsService.java
  src/main/java/com/aptzip/news/service/ThumbnailService.java
  src/main/resources/application-example.properties
Labels: feat

#32 fix: 실거래가 조회 수정
  src/main/java/com/aptzip/dealMap/repository/DealHouseRepository.java
Labels: bug

#37 bug: 등록 상태 코드 201로 변경
  src/main/java/com/aptzip/qna/controller/QnAController.java
Labels: bug

#40 bug: 거래 금액 타입 변경
  src/main/java/com/aptzip/dealMap/dto/response/DealListResponse.java
  src/main/java/com/aptzip/dealMap/dto/response/DetailListResponse.java
  src/main/java/com/aptzip/dealMap/entity/HouseDeal.java
  src/main/java/com/aptzip/dealMap/service/DealMapService.java
Labels: bug

#44 feat: 리뷰 관련 기능 추가
  src/main/java/com/aptzip/common/config/WebSecurityConfig.java
  src/main/java/com/aptzip/common/handler/GlobalExceptionHandler.java
  src/main/java/com/aptzip/review/controller/ReviewController.java
  src/main/java/com/aptzip/review/dto/request/RegistReviewRequest.java
  src/main/java/com/aptzip/review/dto/response/DongReviewListResponse.java
  src/main/java/com/aptzip/review/dto/response/UserReviewListResponse.java
  src/main/java/com/aptzip/review/entity/Review.java
  src/main/java/com/aptzip/review/repository/DongCodeRepository.java
  src/main/java/com/aptzip/review/repository/ReviewRepository.java
  src/main/java/com/aptzip/review/service/ReviewService.java
Labels: feat

#43 feat: 관심 매물 관련 기능 추가
  src/main/java/com/aptzip/interestDeal/controller/InterestSaleController.java
  src/main/java/com/aptzip/interestDeal/dto/request/DeleteInterestSaleRequest.java
  src/main/java/com/aptzip/interestDeal/dto/request/RegistInterestSaleRequest.java
  src/main/java/com/aptzip/interestDeal/dto/response/SaleListResponse.java
  src/main/java/com/aptzip/interestDeal/entity/InterestSale.java
  src/main/java/com/aptzip/interestDeal/respository/InterestSaleRepositiory.java
  src/main/java/com/aptzip/interestDeal/service/InterestSaleService.java
Labels: feat

#47 fix: 사용자별 관심 매물 조회 반환값 수정
  src/main/java/com/aptzip/interestDeal/dto/response/SaleListResponse.java
  src/main/java/com/aptzip/interestDeal/respository/InterestSaleRepositiory.java
  src/main/java/com/aptzip/interestDeal/service/InterestSaleService.java
Labels: fix

#51 fix: 관심 매물 조회 동 코드 추가 및 수정
  src/main/java/com/aptzip/interestDeal/dto/response/SaleListResponse.java
  src/main/java/com/aptzip/interestDeal/entity/InterestSale.java
  src/main/java/com/aptzip/interestDeal/respository/InterestSaleRepositiory.java
  src/main/java/com/aptzip/interestDeal/service/InterestSaleService.java
Labels: fix

#57 fix: 사용자별 관심 지역 반환값 수정
  src/main/java/com/aptzip/interestArea/dto/response/InterestListResponse.java
  src/main/java/com/aptzip/interestArea/service/InterestAreaService.java
Labels: fix

#49 fix: 주변 편의 시설 조회 API 요청 Query 수정
  src/main/java/com/aptzip/amenitiesMap/controller/AmenitiesMapController.java
  src/main/java/com/aptzip/amenitiesMap/dto/request/AmenitiesListRequest.java
  src/main/java/com/aptzip/amenitiesMap/repository/AmenitiesMapRepository.java
  src/main/java/com/aptzip/amenitiesMap/service/AmenitiesMapService.java
Labels: fix

#63 fix: 관심 매물 등록 시 동 코드 추가 수정
  src/main/java/com/aptzip/interestDeal/dto/request/RegistInterestSaleRequest.java
  src/main/java/com/aptzip/interestDeal/service/InterestSaleService.java
Labels: fix

#65 fix: 이미 등록된 관심거래 에러 코드 수정
  src/main/java/com/aptzip/interestDeal/service/InterestSaleService.java
Labels: bug, fix
